# CHINA'S REAL ESTATE DEMAND PREDICTION
## Kaggle Competition

## 1.0 Datasets and Their Structure
1. train CSVs
    * new_house_transactions**
    * pre_owned_house_transactions
    * land_transactions
    * sector_POI
    * city_indexes
    * pre_owned_house_transactions_nearby_sectors
    * city_search_index
    * land_transactions_nearby_sectors
    * new_house_transactions_nearby_sectors
2. test CSV

In [1]:
#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob, os
from sklearn.model_selection import train_test_split, TimeSeriesSplit
from sklearn.metrics import root_mean_squared_error
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import GridSearchCV
import joblib

In [171]:
#Load datasets
# NB: load new house transactions (target is here)
new_house = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/train/new_house_transactions.csv")

# Target variable
TARGET = "amount_new_house_transactions"

# Load all other relevant datasets
pre_owned = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/train/pre_owned_house_transactions.csv")
land = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/train/land_transactions.csv")
poi = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/train/sector_POI.csv")
city_indexes = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/train/city_indexes.csv")
pre_owned_nearby_sectors = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/train/pre_owned_house_transactions_nearby_sectors.csv")
city_search_index = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/train/city_search_index.csv")
land_nearby_sectors = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/train/land_transactions_nearby_sectors.csv")
new_house_nearby_sectors = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/train/new_house_transactions_nearby_sectors.csv")

#Load test data
test_df = pd.read_csv("C:/Users/USER/Downloads/china-real-estate-demand-prediction/test.csv")

In [172]:
# Peek at the new house transactions data
new_house.head()

      month  ... period_new_house_sell_through
0  2019-Jan  ...                          3.78
1  2019-Jan  ...                         12.29
2  2019-Jan  ...                          5.95
3  2019-Jan  ...                         83.95
4  2019-Jan  ...                         14.27

[5 rows x 11 columns]

In [173]:
new_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5433 entries, 0 to 5432
Data columns (total 11 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   month                                        5433 non-null   object
 1   sector                                       5433 non-null   object
 2   num_new_house_transactions                   5433 non-null   int64
 3   area_new_house_transactions                  5433 non-null   int64
 4   price_new_house_transactions                 5433 non-null   int64
 5   amount_new_house_transactions                5433 non-null   float64
 6   area_per_unit_new_house_transactions         5433 non-null   int64
 7   total_price_per_unit_new_house_transactions  5433 non-null   float64
 8   num_new_house_available_for_sale             5419 non-null   float64
 9   area_new_house_available_for_sale            5419 non-null   float64
 10  period_new_house_sell_through                5419 non-null   float64
dtypes: float64(5), int64(4), object(2)
memory usage: 467.0+ KB

In [174]:
new_house

         month  ... period_new_house_sell_through
0     2019-Jan  ...                          3.78
1     2019-Jan  ...                         12.29
2     2019-Jan  ...                          5.95
3     2019-Jan  ...                         83.95
4     2019-Jan  ...                         14.27
...        ...  ...                           ...
5428  2024-Jul  ...                         51.82
5429  2024-Jul  ...                         34.76
5430  2024-Jul  ...                         27.74
5431  2024-Jul  ...                         38.62
5432  2024-Jul  ...                          1.39

[5433 rows x 11 columns]

In [175]:
new_house.columns

Index(['month', 'sector', 'num_new_house_transactions',
       'area_new_house_transactions', 'price_new_house_transactions',
       'amount_new_house_transactions', 'area_per_unit_new_house_transactions',
       'total_price_per_unit_new_house_transactions',
       'num_new_house_available_for_sale', 'area_new_house_available_for_sale',
       'period_new_house_sell_through'],
      dtype='object')

In [176]:
#The month column is string and YY-MM format, we need to split it into year and month
new_house[["year", "month"]] = new_house["month"].str.split("-", expand=True)
new_house["year"] = new_house["year"].astype(int)

#Making the Year the first column
new_house = new_house[["year", "month", 'sector', 'num_new_house_transactions',
       'area_new_house_transactions', 'price_new_house_transactions',
       'amount_new_house_transactions', 'area_per_unit_new_house_transactions',
       'total_price_per_unit_new_house_transactions',
       'num_new_house_available_for_sale', 'area_new_house_available_for_sale',
       'period_new_house_sell_through']]

In [177]:
#Viewing the test data
test_df.head()

                  id  new_house_transaction_amount
0  2024 Aug_sector 1                           NaN
1  2024 Aug_sector 2                           NaN
2  2024 Aug_sector 3                           NaN
3  2024 Aug_sector 4                           NaN
4  2024 Aug_sector 5                           NaN

In [178]:
#SPlitting the id column to get year, month and sector
test_df[["year", "rest"]] = test_df["id"].str.split(" ", n=1, expand=True)
test_df[["month", "sector"]] = test_df["rest"].str.split("_", n=1, expand=True)

# Clean types
test_df["year"] = test_df["year"].astype(int)

# Convert Month string ("Jan") -> numeric datetime
#test["month"] = pd.to_datetime(test["month"] + "-" + test["Year"].astype(str), format="%b-%Y")



# Drop helper
test_df = test_df.drop(columns=["rest"])
test_df.head()

                  id  new_house_transaction_amount  year month    sector
0  2024 Aug_sector 1                           NaN  2024   Aug  sector 1
1  2024 Aug_sector 2                           NaN  2024   Aug  sector 2
2  2024 Aug_sector 3                           NaN  2024   Aug  sector 3
3  2024 Aug_sector 4                           NaN  2024   Aug  sector 4
4  2024 Aug_sector 5                           NaN  2024   Aug  sector 5

In [179]:
#Resort the columns
test_df = test_df[["id", "year", "month", "sector"]]
test_df.head()

                  id  year month    sector
0  2024 Aug_sector 1  2024   Aug  sector 1
1  2024 Aug_sector 2  2024   Aug  sector 2
2  2024 Aug_sector 3  2024   Aug  sector 3
3  2024 Aug_sector 4  2024   Aug  sector 4
4  2024 Aug_sector 5  2024   Aug  sector 5

In [180]:
#Merge the test data with new_house data to get the features
test_df = test_df.merge(new_house, on=["year", "month", "sector"], how="left")

In [181]:
test_df

                      id  ...  period_new_house_sell_through
0      2024 Aug_sector 1  ...                            NaN
1      2024 Aug_sector 2  ...                            NaN
2      2024 Aug_sector 3  ...                            NaN
3      2024 Aug_sector 4  ...                            NaN
4      2024 Aug_sector 5  ...                            NaN
...                  ...  ...                            ...
1147  2025 Jul_sector 92  ...                            NaN
1148  2025 Jul_sector 93  ...                            NaN
1149  2025 Jul_sector 94  ...                            NaN
1150  2025 Jul_sector 95  ...                            NaN
1151  2025 Jul_sector 96  ...                            NaN

[1152 rows x 13 columns]

In [182]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1152 entries, 0 to 1151
Data columns (total 13 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   id                                           1152 non-null   object
 1   year                                         1152 non-null   int64
 2   month                                        1152 non-null   object
 3   sector                                       1152 non-null   object
 4   num_new_house_transactions                   0 non-null      float64
 5   area_new_house_transactions                  0 non-null      float64
 6   price_new_house_transactions                 0 non-null      float64
 7   amount_new_house_transactions                0 non-null      float64
 8   area_per_unit_new_house_transactions         0 non-null      float64
 9   total_price_per_unit_new_house_transactions  0 non-null      float64
 10  num_new_house_available_for_sale             0 non-null      float64
 11  area_new_house_available_for_sale            0 non-null      float64
 12  period_new_house_sell_through                0 non-null      float64
dtypes: float64(9), int64(1), object(3)
memory usage: 117.1+ KB

In [183]:
#Viewing the columns in all the datasets
print("Columns in pre_owned dataset: \n", pre_owned.columns)
print("\nColumns in land dataset: \n", land.columns)
print("\nColumns in poi dataset: \n", poi.columns)
print("\nColumns in city_indexes dataset: \n", city_indexes.columns)
print("\nColumns in pre_owned_nearby_sectors dataset: \n", pre_owned_nearby_sectors.columns)
print("\nColumns in city_search_index dataset: \n", city_search_index.columns)
print("\nColumns in land_nearby_sectors dataset: \n", land_nearby_sectors.columns)
print("\nColumns in new_house_nearby_sectors dataset: \n", new_house_nearby_sectors.columns)

Columns in pre_owned dataset:
 Index(['month', 'sector', 'area_pre_owned_house_transactions',
       'amount_pre_owned_house_transactions',
       'num_pre_owned_house_transactions',
       'price_pre_owned_house_transactions'],
      dtype='object')

Columns in land dataset:
 Index(['month', 'sector', 'num_land_transactions', 'construction_area',
       'planned_building_area', 'transaction_amount'],
      dtype='object')

Columns in poi dataset:
 Index(['sector', 'sector_coverage', 'population_scale', 'residential_area',
       'office_building', 'commercial_area', 'resident_population',
       'office_population', 'number_of_shops', 'catering',
       ...
       'medical_health_rehabilitation_institution_dense',
       'medical_health_first_aid_center_dense',
       'medical_health_blood_donation_station_dense',
       'medical_health_disease_prevention_institution_dense',
       'medical_health_general_hospital_dense', 'medical_health_clinic_dense',
       'education_training_school_education_middle_school_dense',
       'education_training_school_education_primary_school_dense',
       'education_training_school_education_kindergarten_dense',
       'education_training_school_education_research_institution_dense'],
      dtype='object', length=142)

Columns in city_indexes dataset:
 Index(['city_indicator_data_year', 'year_end_registered_population_10k',
       'total_households_10k', 'year_end_resident_population_10k',
       'year_end_total_employed_population_10k',
       'year_end_urban_non_private_employees_10k',
       'private_individual_and_other_employees_10k',
       'private_individual_ratio', 'national_year_end_total_population_10k',
       'resident_registered_ratio', 'under_18_10k', '18_60_years_10k',
       'over_60_years_10k', 'total', 'under_18_percent', '18_60_years_percent',
       'over_60_years_percent', 'gdp_100m', 'primary_industry_100m',
       'secondary_industry_100m', 'tertiary_industry_100m',
       'gdp_per_capita_yuan', 'national_gdp_100m', 'national_economic_primacy',
       'national_population_share', 'gdp_population_ratio',
       'secondary_industry_development_gdp_share',
       'tertiary_industry_development_gdp_share', 'employed_population',
       'primary_industry_percent', 'secondary_industry_percent',
       'tertiary_industry_percent',
       'white_collar_service_vs_blue_collar_manufacturing_ratio',
       'general_public_budget_revenue_100m', 'personal_income_tax_100m',
       'per_capita_personal_income_tax_yuan',
       'general_public_budget_expenditure_100m',
       'total_retail_sales_of_consumer_goods_100m', 'retail_sales_growth_rate',
       'urban_consumer_price_index_previous_year_100',
       'annual_average_wage_urban_non_private_employees_yuan',
       'annual_average_wage_urban_non_private_on_duty_employees_yuan',
       'per_capita_disposable_income_absolute_yuan',
       'per_capita_disposable_income_index_previous_year_100',
       'engel_coefficient', 'per_capita_housing_area_sqm',
       'number_of_universities', 'university_students_10k',
       'number_of_middle_schools', 'middle_school_students_10k',
       'number_of_primary_schools', 'primary_school_students_10k',
       'number_of_kindergartens', 'kindergarten_students_10k',
       'hospitals_health_centers', 'hospital_beds_10k',
       'health_technical_personnel_10k', 'doctors_10k', 'road_length_km',
       'road_area_10k_sqm', 'per_capita_urban_road_area_sqm',
       'number_of_operating_bus_lines', 'operating_bus_line_length_km',
       'internet_broadband_access_subscribers_10k',
       'internet_broadband_access_ratio',
       'number_of_industrial_enterprises_above_designated_size',
       'total_current_assets_10k', 'total_fixed_assets_10k',
       'main_business_taxes_and_surcharges_10k',
       'total_fixed_asset_investment_10k',
       'real_estate_development_investment_completed_10k',
       'residential_development_investment_completed_10k',
       'science_expenditure_10k', 'education_expenditure_10k'],
      dtype='object')

Columns in pre_owned_nearby_sectors dataset:
 Index(['month', 'sector', 'num_pre_owned_house_transactions_nearby_sectors',
       'area_pre_owned_house_transactions_nearby_sectors',
       'amount_pre_owned_house_transactions_nearby_sectors',
       'price_pre_owned_house_transactions_nearby_sectors'],
      dtype='object')

Columns in city_search_index dataset:
 Index(['month', 'keyword', 'source', 'search_volume'], dtype='object')

Columns in land_nearby_sectors dataset:
 Index(['month', 'sector', 'num_land_transactions_nearby_sectors',
       'construction_area_nearby_sectors',
       'planned_building_area_nearby_sectors',
       'transaction_amount_nearby_sectors'],
      dtype='object')

Columns in new_house_nearby_sectors dataset:
 Index(['month', 'sector', 'num_new_house_transactions_nearby_sectors',
       'area_new_house_transactions_nearby_sectors',
       'price_new_house_transactions_nearby_sectors',
       'amount_new_house_transactions_nearby_sectors',
       'area_per_unit_new_house_transactions_nearby_sectors',
       'total_price_per_unit_new_house_transactions_nearby_sectors',
       'num_new_house_available_for_sale_nearby_sectors',
       'area_new_house_available_for_sale_nearby_sectors',
       'period_new_house_sell_through_nearby_sectors'],
      dtype='object')

In [184]:
pre_owned.head()

      month  ... price_pre_owned_house_transactions
0  2019-Jan  ...                         605.839416
1  2019-Jan  ...                       27066.836490
2  2019-Jan  ...                       23606.729760
3  2019-Jan  ...                       11301.439410
4  2019-Jan  ...                       51821.651750

[5 rows x 6 columns]

In [185]:
pre_owned.columns

Index(['month', 'sector', 'area_pre_owned_house_transactions',
       'amount_pre_owned_house_transactions',
       'num_pre_owned_house_transactions',
       'price_pre_owned_house_transactions'],
      dtype='object')

In [186]:
#Splitting the month column into year and month
pre_owned[["year", "month"]] = pre_owned["month"].str.split("-", expand=True)
pre_owned["year"] = pre_owned["year"].astype(int)

#Making the Year the first column
pre_owned = pre_owned[["year", "month", 'sector', 'area_pre_owned_house_transactions',
       'amount_pre_owned_house_transactions',
       'num_pre_owned_house_transactions',
       'price_pre_owned_house_transactions']]

In [187]:
pre_owned.head()

   year  ... price_pre_owned_house_transactions
0  2019  ...                         605.839416
1  2019  ...                       27066.836490
2  2019  ...                       23606.729760
3  2019  ...                       11301.439410
4  2019  ...                       51821.651750

[5 rows x 7 columns]

In [188]:
land.head()

      month     sector  ...  planned_building_area  transaction_amount
0  2019-Jan  sector 74  ...                    0.0                 0.0
1  2019-Jan  sector 35  ...                    0.0                 0.0
2  2019-Jan  sector 23  ...                    0.0                 0.0
3  2019-Jan  sector 80  ...                    0.0                 0.0
4  2019-Jan  sector 53  ...                    0.0                 0.0

[5 rows x 6 columns]

In [189]:
land.columns

Index(['month', 'sector', 'num_land_transactions', 'construction_area',
       'planned_building_area', 'transaction_amount'],
      dtype='object')

In [190]:
#Splitting the month column into year and month
land[["year", "month"]] = land["month"].str.split("-", expand=True)
land["year"] = land["year"].astype(int)
#Making the Year the first column
land = land[['year', 'month', 'sector', 'num_land_transactions', 'construction_area',
       'planned_building_area', 'transaction_amount']]
land.head()

   year month  ... planned_building_area  transaction_amount
0  2019   Jan  ...                   0.0                 0.0
1  2019   Jan  ...                   0.0                 0.0
2  2019   Jan  ...                   0.0                 0.0
3  2019   Jan  ...                   0.0                 0.0
4  2019   Jan  ...                   0.0                 0.0

[5 rows x 7 columns]

In [191]:
pre_owned_nearby_sectors.head()

      month  ... price_pre_owned_house_transactions_nearby_sectors
0  2019-Jan  ...                                       17012.79673
1  2019-Jan  ...                                       39108.90208
2  2019-Jan  ...                                       23301.43755
3  2019-Jan  ...                                       37225.81904
4  2019-Jan  ...                                       41984.16747

[5 rows x 6 columns]

In [192]:
#SPlitting the month column in pre_owned_nearby_sectors to year and month
pre_owned_nearby_sectors[["year", "month"]] = pre_owned_nearby_sectors["month"].str.split("-", expand=True)
pre_owned_nearby_sectors["year"] = pre_owned_nearby_sectors["year"].astype(int)
pre_owned_nearby_sectors.head()

  month    sector  ...  price_pre_owned_house_transactions_nearby_sectors  year
0   Jan  sector 1  ...                                        17012.79673  2019
1   Jan  sector 2  ...                                        39108.90208  2019
2   Jan  sector 3  ...                                        23301.43755  2019
3   Jan  sector 4  ...                                        37225.81904  2019
4   Jan  sector 5  ...                                        41984.16747  2019

[5 rows x 7 columns]

In [193]:
#Making the Year the first column
pre_owned_nearby_sectors = pre_owned_nearby_sectors[['year', 'month', 'sector', 'num_pre_owned_house_transactions_nearby_sectors',
       'area_pre_owned_house_transactions_nearby_sectors',
       'amount_pre_owned_house_transactions_nearby_sectors',
       'price_pre_owned_house_transactions_nearby_sectors']]
pre_owned_nearby_sectors.head()

   year  ... price_pre_owned_house_transactions_nearby_sectors
0  2019  ...                                       17012.79673
1  2019  ...                                       39108.90208
2  2019  ...                                       23301.43755
3  2019  ...                                       37225.81904
4  2019  ...                                       41984.16747

[5 rows x 7 columns]

In [194]:
city_search_index.head()

      month keyword source  search_volume
0  2019-Jan      买房    PC端           1914
1  2019-Jan      买房    移动端           2646
2  2019-Jan   二手房市场    PC端            192
3  2019-Jan   二手房市场    移动端            204
4  2019-Jan     公积金    PC端           9160

In [195]:
#SPlitting the month column of city_search_index to year and month
city_search_index[["year", "month"]] = city_search_index["month"].str.split("-", expand=True)
city_search_index["year"] = city_search_index["year"].astype(int)
#Making the Year the first column
city_search_index = city_search_index[['year', 'month', 'keyword', 'source', 'search_volume']]
city_search_index.head()

   year month keyword source  search_volume
0  2019   Jan      买房    PC端           1914
1  2019   Jan      买房    移动端           2646
2  2019   Jan   二手房市场    PC端            192
3  2019   Jan   二手房市场    移动端            204
4  2019   Jan     公积金    PC端           9160

In [196]:
land_nearby_sectors.head()

      month  ... transaction_amount_nearby_sectors
0  2019-Jan  ...                               0.0
1  2019-Jan  ...                               0.0
2  2019-Jan  ...                               0.0
3  2019-Jan  ...                               0.0
4  2019-Jan  ...                               0.0

[5 rows x 6 columns]

In [197]:
land_nearby_sectors.columns

Index(['month', 'sector', 'num_land_transactions_nearby_sectors',
       'construction_area_nearby_sectors',
       'planned_building_area_nearby_sectors',
       'transaction_amount_nearby_sectors'],
      dtype='object')

In [198]:
#Splitting the month column of land_nearby_sectors to year and month
land_nearby_sectors[["year", "month"]] = land_nearby_sectors["month"].str.split("-", expand=True)
land_nearby_sectors["year"] = land_nearby_sectors["year"].astype(int)
#Making the Year the first column
land_nearby_sectors = land_nearby_sectors[['year', 'month', 'sector', 'num_land_transactions_nearby_sectors',
       'construction_area_nearby_sectors',
       'planned_building_area_nearby_sectors',
       'transaction_amount_nearby_sectors']]
land_nearby_sectors.head()

   year  ... transaction_amount_nearby_sectors
0  2019  ...                               0.0
1  2019  ...                               0.0
2  2019  ...                               0.0
3  2019  ...                               0.0
4  2019  ...                               0.0

[5 rows x 7 columns]

In [199]:
new_house_nearby_sectors.head()

      month  ... period_new_house_sell_through_nearby_sectors
0  2019-Jan  ...                                    21.910000
1  2019-Jan  ...                                    11.150000
2  2019-Jan  ...                                    10.467143
3  2019-Jan  ...                                    15.613333
4  2019-Jan  ...                                    26.246000

[5 rows x 11 columns]

In [200]:
new_house_nearby_sectors.columns

Index(['month', 'sector', 'num_new_house_transactions_nearby_sectors',
       'area_new_house_transactions_nearby_sectors',
       'price_new_house_transactions_nearby_sectors',
       'amount_new_house_transactions_nearby_sectors',
       'area_per_unit_new_house_transactions_nearby_sectors',
       'total_price_per_unit_new_house_transactions_nearby_sectors',
       'num_new_house_available_for_sale_nearby_sectors',
       'area_new_house_available_for_sale_nearby_sectors',
       'period_new_house_sell_through_nearby_sectors'],
      dtype='object')

In [201]:
#Splitting the month column of nwe_house_nearby_sectors to year and month
new_house_nearby_sectors[["year", "month"]] = new_house_nearby_sectors["month"].str.split("-", expand=True)
new_house_nearby_sectors["year"] = new_house_nearby_sectors["year"].astype(int)
#Making the Year the first column
new_house_nearby_sectors = new_house_nearby_sectors[['year', 'month', 'sector', 'num_new_house_transactions_nearby_sectors',
       'area_new_house_transactions_nearby_sectors',
       'price_new_house_transactions_nearby_sectors',
       'amount_new_house_transactions_nearby_sectors',
       'area_per_unit_new_house_transactions_nearby_sectors',
       'total_price_per_unit_new_house_transactions_nearby_sectors',
       'num_new_house_available_for_sale_nearby_sectors',
       'area_new_house_available_for_sale_nearby_sectors',
       'period_new_house_sell_through_nearby_sectors']]
new_house_nearby_sectors.head()

   year  ... period_new_house_sell_through_nearby_sectors
0  2019  ...                                    21.910000
1  2019  ...                                    11.150000
2  2019  ...                                    10.467143
3  2019  ...                                    15.613333
4  2019  ...                                    26.246000

[5 rows x 12 columns]

In [202]:
# Merge datasets to create a training set
train_df = (
    new_house
    .merge(pre_owned, on=["year","month","sector"], how="left")
    .merge(pre_owned_nearby_sectors, on=["year","month","sector"], how="left")
    .merge(land, on=["year","month","sector"], how="left")
    .merge(land_nearby_sectors, on=["year","month","sector"], how="left")
    .merge(new_house_nearby_sectors, on=["year","month","sector"], how="left")
    .merge(city_search_index, on=["year","month"], how="left")
    .merge(city_indexes,left_on="year", right_on="city_indicator_data_year", how="left")
    .merge(poi, on=["sector"], how="left")
)
train_df.head()

   year  ... education_training_school_education_research_institution_dense
0  2019  ...                                           0.000014
1  2019  ...                                           0.000014
2  2019  ...                                           0.000014
3  2019  ...                                           0.000014
4  2019  ...                                           0.000014

[5 rows x 255 columns]

In [203]:
#Merge test data with other datasets
test_df = (
    test_df
    .merge(pre_owned, on=["year","month","sector"], how="left")
    .merge(pre_owned_nearby_sectors, on=["year","month","sector"], how="left")
    .merge(land, on=["year","month","sector"], how="left")
    .merge(land_nearby_sectors, on=["year","month","sector"], how="left")
    .merge(new_house_nearby_sectors, on=["year","month","sector"], how="left")
    .merge(city_search_index, on=["year","month"], how="left")
    .merge(city_indexes,left_on="year", right_on="city_indicator_data_year", how="left")
    .merge(poi, on=["sector"], how="left")
)
test_df.head()

                  id  ...  education_training_school_education_research_institution_dense
0  2024 Aug_sector 1  ...                                       1.380000e-05
1  2024 Aug_sector 2  ...                                       3.070000e-07
2  2024 Aug_sector 3  ...                                                NaN
3  2024 Aug_sector 4  ...                                       0.000000e+00
4  2024 Aug_sector 5  ...                                       0.000000e+00

[5 rows x 256 columns]

In [204]:
print(train_df.shape, test_df.shape)

(385140, 255) (1152, 256)

In [205]:
train_df.isnull().sum()

year                                                                  0
month                                                                 0
sector                                                                0
num_new_house_transactions                                            0
area_new_house_transactions                                           0
                                                                  ...
medical_health_clinic_dense                                       35100
education_training_school_education_middle_school_dense           35100
education_training_school_education_primary_school_dense          35100
education_training_school_education_kindergarten_dense            35100
education_training_school_education_research_institution_dense    35100
Length: 255, dtype: int64

In [206]:
test_df.isnull().sum()

id                                                                   0
year                                                                 0
month                                                                0
sector                                                               0
num_new_house_transactions                                        1152
                                                                  ...
medical_health_clinic_dense                                        120
education_training_school_education_middle_school_dense            120
education_training_school_education_primary_school_dense           120
education_training_school_education_kindergarten_dense             120
education_training_school_education_research_institution_dense     120
Length: 256, dtype: int64

In [207]:
#Determine columns with more than 120 missing values
cols_to_drop = test_df.columns[test_df.isnull().sum() > 120].to_list().copy()
cols_to_drop

['num_new_house_transactions',
 'area_new_house_transactions',
 'price_new_house_transactions',
 'amount_new_house_transactions',
 'area_per_unit_new_house_transactions',
 'total_price_per_unit_new_house_transactions',
 'num_new_house_available_for_sale',
 'area_new_house_available_for_sale',
 'period_new_house_sell_through',
 'area_pre_owned_house_transactions',
 'amount_pre_owned_house_transactions',
 'num_pre_owned_house_transactions',
 'price_pre_owned_house_transactions',
 'num_pre_owned_house_transactions_nearby_sectors',
 'area_pre_owned_house_transactions_nearby_sectors',
 'amount_pre_owned_house_transactions_nearby_sectors',
 'price_pre_owned_house_transactions_nearby_sectors',
 'num_land_transactions',
 'construction_area',
 'planned_building_area',
 'transaction_amount',
 'num_land_transactions_nearby_sectors',
 'construction_area_nearby_sectors',
 'planned_building_area_nearby_sectors',
 'transaction_amount_nearby_sectors',
 'num_new_house_transactions_nearby_sectors',
 'area_new_house_transactions_nearby_sectors',
 'price_new_house_transactions_nearby_sectors',
 'amount_new_house_transactions_nearby_sectors',
 'area_per_unit_new_house_transactions_nearby_sectors',
 'total_price_per_unit_new_house_transactions_nearby_sectors',
 'num_new_house_available_for_sale_nearby_sectors',
 'area_new_house_available_for_sale_nearby_sectors',
 'period_new_house_sell_through_nearby_sectors',
 'keyword',
 'source',
 'search_volume',
 'city_indicator_data_year',
 'year_end_registered_population_10k',
 'total_households_10k',
 'year_end_resident_population_10k',
 'year_end_total_employed_population_10k',
 'year_end_urban_non_private_employees_10k',
 'private_individual_and_other_employees_10k',
 'private_individual_ratio',
 'national_year_end_total_population_10k',
 'resident_registered_ratio',
 'under_18_10k',
 '18_60_years_10k',
 'over_60_years_10k',
 'total',
 'under_18_percent',
 '18_60_years_percent',
 'over_60_years_percent',
 'gdp_100m',
 'primary_industry_100m',
 'secondary_industry_100m',
 'tertiary_industry_100m',
 'gdp_per_capita_yuan',
 'national_gdp_100m',
 'national_economic_primacy',
 'national_population_share',
 'gdp_population_ratio',
 'secondary_industry_development_gdp_share',
 'tertiary_industry_development_gdp_share',
 'employed_population',
 'primary_industry_percent',
 'secondary_industry_percent',
 'tertiary_industry_percent',
 'white_collar_service_vs_blue_collar_manufacturing_ratio',
 'general_public_budget_revenue_100m',
 'personal_income_tax_100m',
 'per_capita_personal_income_tax_yuan',
 'general_public_budget_expenditure_100m',
 'total_retail_sales_of_consumer_goods_100m',
 'retail_sales_growth_rate',
 'urban_consumer_price_index_previous_year_100',
 'annual_average_wage_urban_non_private_employees_yuan',
 'annual_average_wage_urban_non_private_on_duty_employees_yuan',
 'per_capita_disposable_income_absolute_yuan',
 'per_capita_disposable_income_index_previous_year_100',
 'engel_coefficient',
 'per_capita_housing_area_sqm',
 'number_of_universities',
 'university_students_10k',
 'number_of_middle_schools',
 'middle_school_students_10k',
 'number_of_primary_schools',
 'primary_school_students_10k',
 'number_of_kindergartens',
 'kindergarten_students_10k',
 'hospitals_health_centers',
 'hospital_beds_10k',
 'health_technical_personnel_10k',
 'doctors_10k',
 'road_length_km',
 'road_area_10k_sqm',
 'per_capita_urban_road_area_sqm',
 'number_of_operating_bus_lines',
 'operating_bus_line_length_km',
 'internet_broadband_access_subscribers_10k',
 'internet_broadband_access_ratio',
 'number_of_industrial_enterprises_above_designated_size',
 'total_current_assets_10k',
 'total_fixed_assets_10k',
 'main_business_taxes_and_surcharges_10k',
 'total_fixed_asset_investment_10k',
 'real_estate_development_investment_completed_10k',
 'residential_development_investment_completed_10k',
 'science_expenditure_10k',
 'education_expenditure_10k',
 'surrounding_housing_average_price',
 'surrounding_shop_average_rent']

In [208]:
#Droppin columns in test_df where sum of missing data is greater than 120
test_df = test_df.drop(columns=cols_to_drop)
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1152 entries, 0 to 1151
Columns: 143 entries, id to education_training_school_education_research_institution_dense
dtypes: float64(139), int64(1), object(3)
memory usage: 1.3+ MB

In [210]:
test_df

                      id  ...  education_training_school_education_research_institution_dense
0      2024 Aug_sector 1  ...                                       1.380000e-05
1      2024 Aug_sector 2  ...                                       3.070000e-07
2      2024 Aug_sector 3  ...                                                NaN
3      2024 Aug_sector 4  ...                                       0.000000e+00
4      2024 Aug_sector 5  ...                                       0.000000e+00
...                  ...  ...                                                ...
1147  2025 Jul_sector 92  ...                                       1.400000e-07
1148  2025 Jul_sector 93  ...                                       0.000000e+00
1149  2025 Jul_sector 94  ...                                       1.080000e-07
1150  2025 Jul_sector 95  ...                                       6.060000e-05
1151  2025 Jul_sector 96  ...                                       1.350000e-05

[1152 rows x 143 columns]

In [211]:
test_df.select_dtypes(include="object").columns

Index(['id', 'month', 'sector'], dtype='object')

In [214]:
cols_to_drop

['num_new_house_transactions',
 'area_new_house_transactions',
 'price_new_house_transactions',
 'amount_new_house_transactions',
 'area_per_unit_new_house_transactions',
 'total_price_per_unit_new_house_transactions',
 'num_new_house_available_for_sale',
 'area_new_house_available_for_sale',
 'period_new_house_sell_through',
 'area_pre_owned_house_transactions',
 'amount_pre_owned_house_transactions',
 'num_pre_owned_house_transactions',
 'price_pre_owned_house_transactions',
 'num_pre_owned_house_transactions_nearby_sectors',
 'area_pre_owned_house_transactions_nearby_sectors',
 'amount_pre_owned_house_transactions_nearby_sectors',
 'price_pre_owned_house_transactions_nearby_sectors',
 'num_land_transactions',
 'construction_area',
 'planned_building_area',
 'transaction_amount',
 'num_land_transactions_nearby_sectors',
 'construction_area_nearby_sectors',
 'planned_building_area_nearby_sectors',
 'transaction_amount_nearby_sectors',
 'num_new_house_transactions_nearby_sectors',
 'area_new_house_transactions_nearby_sectors',
 'price_new_house_transactions_nearby_sectors',
 'amount_new_house_transactions_nearby_sectors',
 'area_per_unit_new_house_transactions_nearby_sectors',
 'total_price_per_unit_new_house_transactions_nearby_sectors',
 'num_new_house_available_for_sale_nearby_sectors',
 'area_new_house_available_for_sale_nearby_sectors',
 'period_new_house_sell_through_nearby_sectors',
 'keyword',
 'source',
 'search_volume',
 'city_indicator_data_year',
 'year_end_registered_population_10k',
 'total_households_10k',
 'year_end_resident_population_10k',
 'year_end_total_employed_population_10k',
 'year_end_urban_non_private_employees_10k',
 'private_individual_and_other_employees_10k',
 'private_individual_ratio',
 'national_year_end_total_population_10k',
 'resident_registered_ratio',
 'under_18_10k',
 '18_60_years_10k',
 'over_60_years_10k',
 'total',
 'under_18_percent',
 '18_60_years_percent',
 'over_60_years_percent',
 'gdp_100m',
 'primary_industry_100m',
 'secondary_industry_100m',
 'tertiary_industry_100m',
 'gdp_per_capita_yuan',
 'national_gdp_100m',
 'national_economic_primacy',
 'national_population_share',
 'gdp_population_ratio',
 'secondary_industry_development_gdp_share',
 'tertiary_industry_development_gdp_share',
 'employed_population',
 'primary_industry_percent',
 'secondary_industry_percent',
 'tertiary_industry_percent',
 'white_collar_service_vs_blue_collar_manufacturing_ratio',
 'general_public_budget_revenue_100m',
 'personal_income_tax_100m',
 'per_capita_personal_income_tax_yuan',
 'general_public_budget_expenditure_100m',
 'total_retail_sales_of_consumer_goods_100m',
 'retail_sales_growth_rate',
 'urban_consumer_price_index_previous_year_100',
 'annual_average_wage_urban_non_private_employees_yuan',
 'annual_average_wage_urban_non_private_on_duty_employees_yuan',
 'per_capita_disposable_income_absolute_yuan',
 'per_capita_disposable_income_index_previous_year_100',
 'engel_coefficient',
 'per_capita_housing_area_sqm',
 'number_of_universities',
 'university_students_10k',
 'number_of_middle_schools',
 'middle_school_students_10k',
 'number_of_primary_schools',
 'primary_school_students_10k',
 'number_of_kindergartens',
 'kindergarten_students_10k',
 'hospitals_health_centers',
 'hospital_beds_10k',
 'health_technical_personnel_10k',
 'doctors_10k',
 'road_length_km',
 'road_area_10k_sqm',
 'per_capita_urban_road_area_sqm',
 'number_of_operating_bus_lines',
 'operating_bus_line_length_km',
 'internet_broadband_access_subscribers_10k',
 'internet_broadband_access_ratio',
 'number_of_industrial_enterprises_above_designated_size',
 'total_current_assets_10k',
 'total_fixed_assets_10k',
 'main_business_taxes_and_surcharges_10k',
 'total_fixed_asset_investment_10k',
 'real_estate_development_investment_completed_10k',
 'residential_development_investment_completed_10k',
 'science_expenditure_10k',
 'education_expenditure_10k',
 'surrounding_housing_average_price',
 'surrounding_shop_average_rent']

In [219]:
train_df

        year  ... education_training_school_education_research_institution_dense
0       2019  ...                                           0.000014
1       2019  ...                                           0.000014
2       2019  ...                                           0.000014
3       2019  ...                                           0.000014
4       2019  ...                                           0.000014
...      ...  ...                                                ...
385135  2024  ...                                           0.000013
385136  2024  ...                                           0.000013
385137  2024  ...                                           0.000013
385138  2024  ...                                           0.000013
385139  2024  ...                                           0.000013

[385140 rows x 255 columns]

In [271]:
cols_to_drop_clean = [c for c in cols_to_drop if c != TARGET]

In [272]:
train = train_df.drop(columns=cols_to_drop_clean).drop_duplicates()
train.shape

(5433, 143)

In [273]:
train.head()

     year  ... education_training_school_education_research_institution_dense
0    2019  ...                                       1.380000e-05
60   2019  ...                                       3.070000e-07
120  2019  ...                                       0.000000e+00
180  2019  ...                                       0.000000e+00
240  2019  ...                                       1.110000e-07

[5 rows x 143 columns]

In [274]:

#Handle missing values & select features
# ==========================================
# Drop identifiers and target for training features
target = "amount_new_house_transactions"
X = train.drop(columns=[target])
y = train[target]

# Basic preprocessing: fill NA
X = X.fillna(0)

In [275]:
X

        year  ... education_training_school_education_research_institution_dense
0       2019  ...                                       1.380000e-05
60      2019  ...                                       3.070000e-07
120     2019  ...                                       0.000000e+00
180     2019  ...                                       0.000000e+00
240     2019  ...                                       1.110000e-07
...      ...  ...                                                ...
384840  2024  ...                                       1.520000e-06
384900  2024  ...                                       1.400000e-07
384960  2024  ...                                       0.000000e+00
385020  2024  ...                                       1.080000e-07
385080  2024  ...                                       1.350000e-05

[5433 rows x 142 columns]

In [276]:
# Encode categorical (like sector) simply with factorize
#for col in X.select_dtypes(include="object").columns:
    #X[col], _ = pd.factorize(X[col])

#print("Feature matrix shape:", X.shape)
X = X.select_dtypes(exclude="object").drop(columns=["year"])
X.head()

     sector_coverage  ...  education_training_school_education_research_institution_dense
0           0.311873  ...                                       1.380000e-05
60          0.556383  ...                                       3.070000e-07
120         0.128257  ...                                       0.000000e+00
180         0.964502  ...                                       0.000000e+00
240         0.590093  ...                                       1.110000e-07

[5 rows x 139 columns]

In [277]:
test = test_df.select_dtypes(exclude="object").drop(columns=["year"])
test

      sector_coverage  ...  education_training_school_education_research_institution_dense
0            0.311873  ...                                       1.380000e-05
1            0.556383  ...                                       3.070000e-07
2                 NaN  ...                                                NaN
3            0.128257  ...                                       0.000000e+00
4            0.964502  ...                                       0.000000e+00
...               ...  ...                                                ...
1147         0.529826  ...                                       1.400000e-07
1148         0.184127  ...                                       0.000000e+00
1149         0.193489  ...                                       1.080000e-07
1150         1.422036  ...                                       6.060000e-05
1151         0.983634  ...                                       1.350000e-05

[1152 rows x 139 columns]

In [278]:
#Handle missing values in test set
test = test.fillna(0)
#Encode categorical (like sector) simply with factorize
#for col in test.select_dtypes(include="object").columns:
    #test[col], _ = pd.factorize(test[col])
#print("Test feature matrix shape:", test.shape)

In [279]:
test.head()

   sector_coverage  ...  education_training_school_education_research_institution_dense
0         0.311873  ...                                       1.380000e-05
1         0.556383  ...                                       3.070000e-07
2         0.000000  ...                                       0.000000e+00
3         0.128257  ...                                       0.000000e+00
4         0.964502  ...                                       0.000000e+00

[5 rows x 139 columns]

In [280]:
X.head()

     sector_coverage  ...  education_training_school_education_research_institution_dense
0           0.311873  ...                                       1.380000e-05
60          0.556383  ...                                       3.070000e-07
120         0.128257  ...                                       0.000000e+00
180         0.964502  ...                                       0.000000e+00
240         0.590093  ...                                       1.110000e-07

[5 rows x 139 columns]

In [281]:
y.isna().any()

np.False_

In [282]:
#SSet the X_train and y_train
X_train = X
y_train = y
X_test = test

In [283]:
X_train.shape

(5433, 139)

In [284]:
y_train.shape

(5433,)

In [285]:
X_test.shape

(1152, 139)

In [286]:
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42)

In [287]:
# Train XGBoost
xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    tree_method="hist"
)

xgb_model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=50)

[0]	validation_0-rmse:45938.03387
[50]	validation_0-rmse:36985.38681
[100]	validation_0-rmse:37026.12242
[150]	validation_0-rmse:37050.46168
[200]	validation_0-rmse:37011.27423
[250]	validation_0-rmse:37069.20815
[300]	validation_0-rmse:37009.50190
[350]	validation_0-rmse:37098.23029
[400]	validation_0-rmse:36994.36866
[450]	validation_0-rmse:37043.41199
[499]	validation_0-rmse:37049.76275

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [288]:
#Predict model on validation
val_preds = xgb_model.predict(X_val)
rmse = (root_mean_squared_error(y_val, val_preds))
print(f"Validation RMSE: {rmse:.4f}")

Validation RMSE: 37049.7629

In [289]:
#Predict model on test
test_preds = xgb_model.predict(X_test)

In [290]:
submission2 = test_df[["id"]].copy()
submission2["new_house_transaction_amount"] = test_preds
submission2.head()

                  id  new_house_transaction_amount
0  2024 Aug_sector 1                  25842.373047
1  2024 Aug_sector 2                  12555.369141
2  2024 Aug_sector 3                  25917.417969
3  2024 Aug_sector 4                  75543.015625
4  2024 Aug_sector 5                   1798.687866

In [291]:
#SUbmission file
submission2.to_csv("submission3.csv", index=False)

In [292]:
submission2.shape

(1152, 2)

In [86]:
new_house

      year month     sector  amount_new_house_transactions
0     2019   Jan   sector 1                       13827.14
1     2019   Jan   sector 2                       28277.73
2     2019   Jan   sector 4                        1424.21
3     2019   Jan   sector 5                         792.10
4     2019   Jan   sector 6                         607.94
...    ...   ...        ...                            ...
5428  2024   Jul  sector 91                       32450.06
5429  2024   Jul  sector 92                       30804.74
5430  2024   Jul  sector 93                       22335.30
5431  2024   Jul  sector 94                       13389.41
5432  2024   Jul  sector 96                         561.19

[5433 rows x 4 columns]